import { Professional } from "./types"

export const mockProfessionals: Professional[] = [
  {
    id: "1",
    name: "Dr. Sarah Chen",
    credentials: "PhD, CCC-SLP",
    specialty: "Speech Therapy",
    treatmentType: "Conventional",
    conditions: ["Autism Spectrum Disorder", "Speech Delays", "Developmental Delays"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0195, lng: -118.4912 },
    bio: "Dr. Chen specializes in evidence-based speech therapy for neurodivergent children, with over 15 years of experience working with children on the autism spectrum.",
    philosophy: "I believe in meeting each child where they are and building on their unique strengths. My approach combines structured intervention with play-based learning.",
    experience: "15+ years",
    availability: "Monday-Friday, 9am-5pm",
    isRecommended: true,
    rating: 4.9,
    reviewCount: 127,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English", "Mandarin"],
    insuranceAccepted: ["Aetna", "Blue Cross", "Cigna"],
    yearsExperience: 15,
    imageUrl: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "2",
    name: "Maya Patel",
    credentials: "OTR/L, SIT Certified",
    specialty: "Sensory Integration",
    treatmentType: "Both",
    conditions: ["Sensory Processing", "Autism Spectrum Disorder", "Anxiety"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0259, lng: -118.4816 },
    bio: "Certified in Sensory Integration Therapy, Maya creates individualized sensory diets to help children regulate and thrive in daily activities.",
    philosophy: "Through carefully designed sensory experiences, children can develop better regulation skills and confidence in their bodies.",
    experience: "10 years",
    availability: "Tuesday-Saturday, 10am-6pm",
    isRecommended: true,
    rating: 4.8,
    reviewCount: 94,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English", "Hindi", "Gujarati"],
    insuranceAccepted: ["United Healthcare", "Cigna"],
    yearsExperience: 10,
    imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "3",
    name: "James Rodriguez",
    credentials: "RYT-500, Child Yoga Specialist",
    specialty: "Yoga & Mindfulness",
    treatmentType: "Alternative",
    conditions: ["Anxiety", "Sensory Processing", "ADHD"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0154, lng: -118.4966 },
    bio: "James teaches breathing techniques and gentle yoga specifically designed for neurodivergent children to manage anxiety and improve focus.",
    philosophy: "Mindful movement and breathing practices empower children with tools they can use anywhere, anytime to self-regulate.",
    experience: "8 years",
    availability: "Weekdays 3pm-7pm, Weekends 9am-2pm",
    isRecommended: false,
    rating: 4.7,
    reviewCount: 63,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English", "Spanish"],
    insuranceAccepted: [],
    yearsExperience: 8,
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "4",
    name: "Dr. Emily Morrison",
    credentials: "PsyD, BCBA",
    specialty: "Behavioral Therapy",
    treatmentType: "Conventional",
    conditions: ["Autism Spectrum Disorder", "ADHD", "Developmental Delays"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0328, lng: -118.4895 },
    bio: "Board-certified behavior analyst specializing in Applied Behavior Analysis (ABA) with a naturalistic and compassionate approach.",
    philosophy: "ABA should be child-led and family-centered. I focus on building skills that matter most to each family's daily life.",
    experience: "12 years",
    availability: "Monday-Friday, 8am-4pm",
    isRecommended: false,
    rating: 4.6,
    reviewCount: 81,
    isVerified: true,
    acceptingNewClients: false,
    languages: ["English"],
    insuranceAccepted: ["Aetna", "Blue Cross", "Tricare"],
    yearsExperience: 12,
    imageUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "5",
    name: "Lisa Chang",
    credentials: "LAc, Dipl. OM",
    specialty: "Acupuncture",
    treatmentType: "Alternative",
    conditions: ["Anxiety", "Sensory Processing", "ADHD"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0142, lng: -118.4850 },
    bio: "Licensed acupuncturist with specialized training in pediatric acupuncture and non-needle techniques for children who may be needle-sensitive.",
    philosophy: "Traditional Chinese Medicine offers gentle, holistic support for nervous system regulation without reliance on medication.",
    experience: "14 years",
    availability: "Wednesday-Sunday, 11am-7pm",
    isRecommended: false,
    rating: 4.8,
    reviewCount: 52,
    isVerified: false,
    acceptingNewClients: true,
    languages: ["English", "Mandarin", "Cantonese"],
    insuranceAccepted: [],
    yearsExperience: 14,
    imageUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "6",
    name: "Marcus Johnson",
    credentials: "PT, DPT, PCS",
    specialty: "Physical Therapy",
    treatmentType: "Conventional",
    conditions: ["Developmental Delays", "Sensory Processing", "Autism Spectrum Disorder"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0280, lng: -118.4987 },
    bio: "Pediatric physical therapist helping children develop gross motor skills, coordination, and confidence through movement-based interventions.",
    philosophy: "Every child deserves to move with joy and freedom. I create playful therapy sessions that build strength and coordination.",
    experience: "9 years",
    availability: "Monday-Thursday, 9am-5pm",
    isRecommended: true,
    rating: 4.9,
    reviewCount: 116,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English"],
    insuranceAccepted: ["Aetna", "Blue Cross", "United Healthcare"],
    yearsExperience: 9,
    imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "7",
    name: "Rachel Goldstein",
    credentials: "MA, OTR/L",
    specialty: "Occupational Therapy",
    treatmentType: "Conventional",
    conditions: ["Dyslexia", "ADHD", "Developmental Delays"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0089, lng: -118.4977 },
    bio: "Occupational therapist specializing in handwriting, fine motor skills, and executive function support for children with learning differences.",
    philosophy: "I help children develop the skills they need for school success while honoring their unique learning styles.",
    experience: "11 years",
    availability: "Monday-Friday, 2pm-7pm",
    isRecommended: false,
    rating: 4.7,
    reviewCount: 73,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English", "Hebrew"],
    insuranceAccepted: ["Cigna", "United Healthcare"],
    yearsExperience: 11,
    imageUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "8",
    name: "David Kim",
    credentials: "MT-BC",
    specialty: "Music Therapy",
    treatmentType: "Both",
    conditions: ["Autism Spectrum Disorder", "Anxiety", "Speech Delays"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0245, lng: -118.4793 },
    bio: "Board-certified music therapist using rhythm, melody, and sound to support communication, emotional regulation, and social connection.",
    philosophy: "Music is a universal language that can unlock communication and joy for neurodivergent children.",
    experience: "7 years",
    availability: "Tuesday-Saturday, 10am-6pm",
    isRecommended: true,
    rating: 5.0,
    reviewCount: 45,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English", "Korean"],
    insuranceAccepted: ["Blue Cross"],
    yearsExperience: 7,
    imageUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "9",
    name: "Sophia Martinez",
    credentials: "ATR-BC, LPAT",
    specialty: "Art Therapy",
    treatmentType: "Alternative",
    conditions: ["Anxiety", "Autism Spectrum Disorder", "Sensory Processing"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0301, lng: -118.4768 },
    bio: "Registered art therapist creating safe spaces for nonverbal expression and emotional processing through creative media.",
    philosophy: "Art provides a voice when words are difficult. I meet children in their creative process without judgment.",
    experience: "10 years",
    availability: "Monday, Wednesday, Friday 1pm-8pm",
    isRecommended: false,
    rating: 4.6,
    reviewCount: 38,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English", "Spanish"],
    insuranceAccepted: [],
    yearsExperience: 10,
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "10",
    name: "Dr. Amanda Foster",
    credentials: "PhD, CCC-SLP, TSSLD",
    specialty: "Speech Therapy",
    treatmentType: "Conventional",
    conditions: ["Dyslexia", "Speech Delays", "Developmental Delays"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0111, lng: -118.4892 },
    bio: "Speech-language pathologist specializing in literacy development and reading intervention for children with dyslexia and language-based learning disabilities.",
    philosophy: "Reading challenges are neurological, not motivational. I use multisensory, structured approaches proven to help dyslexic learners succeed.",
    experience: "18 years",
    availability: "Monday-Thursday, 3pm-8pm",
    isRecommended: true,
    rating: 4.9,
    reviewCount: 142,
    isVerified: true,
    acceptingNewClients: false,
    languages: ["English", "French"],
    insuranceAccepted: ["Aetna", "Cigna", "Blue Cross"],
    yearsExperience: 18,
    imageUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "11",
    name: "Nia Williams",
    credentials: "E-RYT 200, Kids Yoga Certified",
    specialty: "Yoga & Mindfulness",
    treatmentType: "Alternative",
    conditions: ["Anxiety", "ADHD", "Sensory Processing"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0219, lng: -118.4945 },
    bio: "Experienced yoga instructor teaching breathing techniques and movement practices specifically designed for children with attention and anxiety challenges.",
    philosophy: "Breath is the bridge between body and mind. I teach children practical tools for self-regulation through gentle, accessible practices.",
    experience: "6 years",
    availability: "Weekends and weekday evenings",
    isRecommended: false,
    rating: 4.8,
    reviewCount: 29,
    isVerified: false,
    acceptingNewClients: true,
    languages: ["English"],
    insuranceAccepted: [],
    yearsExperience: 6,
    imageUrl: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "12",
    name: "Dr. Robert Thompson",
    credentials: "OTD, OTR/L",
    specialty: "Sensory Integration",
    treatmentType: "Conventional",
    conditions: ["Sensory Processing", "Autism Spectrum Disorder", "ADHD"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0167, lng: -118.4777 },
    bio: "Occupational therapist with doctorate-level training in sensory integration, helping children process sensory information more effectively.",
    philosophy: "When we understand a child's sensory needs, we can create environments where they feel safe, regulated, and ready to learn.",
    experience: "13 years",
    availability: "Monday-Friday, 8am-3pm",
    isRecommended: false,
    rating: 4.7,
    reviewCount: 88,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English"],
    insuranceAccepted: ["Aetna", "United Healthcare", "Cigna"],
    yearsExperience: 13,
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "13",
    name: "Dr. Jennifer Lee",
    credentials: "PsyD, Licensed Psychologist",
    specialty: "Behavioral Therapy",
    treatmentType: "Conventional",
    conditions: ["Anxiety", "ADHD", "Autism Spectrum Disorder"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0346, lng: -118.4752 },
    bio: "Clinical psychologist specializing in cognitive behavioral therapy for neurodivergent children and teens, with a focus on anxiety management.",
    philosophy: "I help children understand their thoughts and feelings, developing practical strategies for managing anxiety and building resilience.",
    experience: "16 years",
    availability: "Monday-Thursday, 10am-6pm",
    isRecommended: false,
    rating: 4.8,
    reviewCount: 102,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English", "Korean"],
    insuranceAccepted: ["Aetna", "Blue Cross", "United Healthcare"],
    yearsExperience: 16,
    imageUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "14",
    name: "Michael O'Brien",
    credentials: "LCSW, RPT-S",
    specialty: "Play Therapy",
    treatmentType: "Both",
    conditions: ["Autism Spectrum Disorder", "Anxiety", "Developmental Delays"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0055, lng: -118.4915 },
    bio: "Registered play therapist supervisor using child-centered play therapy to help neurodivergent children express emotions and build coping skills.",
    philosophy: "Play is the natural language of children. Through play, they can process experiences and develop emotional regulation in a safe space.",
    experience: "14 years",
    availability: "Tuesday-Saturday, 9am-5pm",
    isRecommended: false,
    rating: 4.7,
    reviewCount: 67,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English"],
    insuranceAccepted: ["Blue Cross", "Cigna"],
    yearsExperience: 14,
    imageUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "15",
    name: "Dr. Priya Sharma",
    credentials: "MD, Developmental Pediatrician",
    specialty: "Behavioral Therapy",
    treatmentType: "Conventional",
    conditions: ["Autism Spectrum Disorder", "ADHD", "Developmental Delays"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0270, lng: -118.4854 },
    bio: "Board-certified developmental pediatrician providing comprehensive evaluations and coordinated care for children with developmental differences.",
    philosophy: "Every child's developmental journey is unique. I work closely with families to create individualized treatment plans that support their child's growth.",
    experience: "20 years",
    availability: "Monday-Friday, 8am-5pm",
    isRecommended: false,
    rating: 4.9,
    reviewCount: 158,
    isVerified: true,
    acceptingNewClients: false,
    languages: ["English", "Hindi", "Urdu"],
    insuranceAccepted: ["Aetna", "Blue Cross", "United Healthcare", "Cigna"],
    yearsExperience: 20,
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "16",
    name: "Alex Chen",
    credentials: "MS, CCC-SLP",
    specialty: "Speech Therapy",
    treatmentType: "Conventional",
    conditions: ["Speech Delays", "Autism Spectrum Disorder", "Developmental Delays"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0125, lng: -118.4820 },
    bio: "Speech-language pathologist specializing in augmentative and alternative communication (AAC) for minimally verbal children.",
    philosophy: "Communication takes many forms. I help children find their voice, whether through words, signs, or assistive technology.",
    experience: "9 years",
    availability: "Monday-Friday, 9am-4pm",
    isRecommended: false,
    rating: 4.8,
    reviewCount: 76,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English", "Mandarin"],
    insuranceAccepted: ["Blue Cross", "United Healthcare"],
    yearsExperience: 9,
    imageUrl: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "17",
    name: "Dr. Karen Mitchell",
    credentials: "PhD, BCBA-D",
    specialty: "Behavioral Therapy",
    treatmentType: "Conventional",
    conditions: ["Autism Spectrum Disorder", "ADHD", "Developmental Delays"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0095, lng: -118.4992 },
    bio: "Doctoral-level behavior analyst focusing on teaching functional communication and reducing challenging behaviors through positive reinforcement.",
    philosophy: "Behavior is communication. I help families understand what their child is trying to tell them and teach more effective ways to communicate needs.",
    experience: "17 years",
    availability: "Monday-Friday, 7am-3pm",
    isRecommended: false,
    rating: 4.6,
    reviewCount: 94,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English"],
    insuranceAccepted: ["Aetna", "Tricare", "Blue Cross"],
    yearsExperience: 17,
    imageUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "18",
    name: "Javier Morales",
    credentials: "MA, LMFT",
    specialty: "Family Therapy",
    treatmentType: "Both",
    conditions: ["Anxiety", "ADHD", "Autism Spectrum Disorder"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0315, lng: -118.4823 },
    bio: "Licensed marriage and family therapist providing family-centered therapy to support the entire family system in navigating neurodiversity.",
    philosophy: "Neurodiversity affects the whole family. I help families build understanding, communication, and resilience together.",
    experience: "11 years",
    availability: "Tuesday-Friday 2pm-8pm, Saturday 10am-4pm",
    isRecommended: false,
    rating: 4.7,
    reviewCount: 58,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English", "Spanish"],
    insuranceAccepted: ["Cigna", "United Healthcare"],
    yearsExperience: 11,
    imageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "19",
    name: "Dr. Hannah Brooks",
    credentials: "EdD, Educational Therapist",
    specialty: "Educational Therapy",
    treatmentType: "Conventional",
    conditions: ["Dyslexia", "ADHD", "Developmental Delays"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0205, lng: -118.4735 },
    bio: "Educational therapist specializing in evidence-based interventions for reading, writing, and math challenges in neurodivergent learners.",
    philosophy: "Learning differences are not learning disabilities. With the right support and strategies, every child can succeed academically.",
    experience: "15 years",
    availability: "Monday-Thursday, 3pm-7pm",
    isRecommended: false,
    rating: 4.8,
    reviewCount: 84,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English"],
    insuranceAccepted: [],
    yearsExperience: 15,
    imageUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "20",
    name: "Thomas Anderson",
    credentials: "CPT, Exercise Physiologist",
    specialty: "Physical Therapy",
    treatmentType: "Alternative",
    conditions: ["ADHD", "Sensory Processing", "Anxiety"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0183, lng: -118.4968 },
    bio: "Certified personal trainer specializing in movement-based interventions for neurodivergent children, focusing on strength, coordination, and body awareness.",
    philosophy: "Movement is medicine. Regular physical activity can dramatically improve focus, mood, and self-regulation in neurodivergent children.",
    experience: "8 years",
    availability: "Weekdays 4pm-8pm, Weekends flexible",
    isRecommended: false,
    rating: 4.6,
    reviewCount: 41,
    isVerified: false,
    acceptingNewClients: true,
    languages: ["English"],
    insuranceAccepted: [],
    yearsExperience: 8,
    imageUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "21",
    name: "Dr. Olivia Washington",
    credentials: "ND, Naturopathic Doctor",
    specialty: "Nutrition",
    treatmentType: "Alternative",
    conditions: ["ADHD", "Anxiety", "Sensory Processing"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0072, lng: -118.4865 },
    bio: "Naturopathic physician specializing in nutritional interventions and gut-brain connection for neurodivergent children.",
    philosophy: "Nutrition plays a crucial role in brain function and behavior. I help families optimize their child's diet to support optimal development.",
    experience: "12 years",
    availability: "Wednesday-Saturday, 10am-6pm",
    isRecommended: false,
    rating: 4.5,
    reviewCount: 47,
    isVerified: false,
    acceptingNewClients: true,
    languages: ["English"],
    insuranceAccepted: [],
    yearsExperience: 12,
    imageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "22",
    name: "Samuel Park",
    credentials: "OTR/L, DIR/Floortime",
    specialty: "Occupational Therapy",
    treatmentType: "Both",
    conditions: ["Autism Spectrum Disorder", "Developmental Delays", "Sensory Processing"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0289, lng: -118.4901 },
    bio: "Occupational therapist trained in DIR/Floortime methodology, focusing on building relationships and developmental capacities through play.",
    philosophy: "Development happens through relationships. I use play-based interactions to help children build foundation skills for learning and connection.",
    experience: "10 years",
    availability: "Monday-Friday, 9am-5pm",
    isRecommended: false,
    rating: 4.7,
    reviewCount: 62,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English", "Korean"],
    insuranceAccepted: ["Blue Cross", "Cigna"],
    yearsExperience: 10,
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "23",
    name: "Isabella Romano",
    credentials: "MM, Music Therapist",
    specialty: "Music Therapy",
    treatmentType: "Alternative",
    conditions: ["Autism Spectrum Disorder", "Speech Delays", "Sensory Processing"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0138, lng: -118.4706 },
    bio: "Music therapist using instrumental play and songwriting to support communication development and emotional expression in neurodivergent children.",
    philosophy: "Music bypasses many traditional barriers to communication, allowing children to express themselves and connect with others in meaningful ways.",
    experience: "9 years",
    availability: "Monday-Thursday, 11am-7pm",
    isRecommended: false,
    rating: 4.8,
    reviewCount: 55,
    isVerified: true,
    acceptingNewClients: true,
    languages: ["English", "Italian"],
    insuranceAccepted: [],
    yearsExperience: 9,
    imageUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=faces"
  },
  {
    id: "24",
    name: "Dr. William Hayes",
    credentials: "PhD, Neuropsychologist",
    specialty: "Behavioral Therapy",
    treatmentType: "Conventional",
    conditions: ["ADHD", "Dyslexia", "Autism Spectrum Disorder"],
    location: { city: "Santa Monica", state: "CA", lat: 34.0358, lng: -118.4884 },
    bio: "Clinical neuropsychologist conducting comprehensive evaluations to understand each child's cognitive strengths and challenges.",
    philosophy: "Understanding how a child's brain works is the first step to helping them succeed. I provide detailed assessments that guide effective interventions.",
    experience: "22 years",
    availability: "Monday-Thursday, 9am-5pm",
    isRecommended: false,
    rating: 4.9,
    reviewCount: 112,
    isVerified: true,
    acceptingNewClients: false,
    languages: ["English"],
    insuranceAccepted: ["Aetna", "Blue Cross", "United Healthcare"],
    yearsExperience: 22,
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=faces"
  }
]
