import { Professional } from "./types"

export const mockProfessionals: Professional[] = [
  {
    id: "1",
    name: "Dr. Sarah Chen",
    credentials: "PhD, CCC-SLP",
    specialty: "Speech Therapy",
    treatmentType: "Conventional",
    conditions: ["Autism Spectrum Disorder", "Speech Delays", "Developmental Delays"],
    location: { city: "Washington", state: "DC" },
    bio: "Dr. Chen specializes in evidence-based speech therapy for neurodivergent children, with over 15 years of experience working with children on the autism spectrum.",
    philosophy: "I believe in meeting each child where they are and building on their unique strengths. My approach combines structured intervention with play-based learning.",
    experience: "15+ years",
    availability: "Monday-Friday, 9am-5pm",
    isRecommended: true
  },
  {
    id: "2",
    name: "Maya Patel",
    credentials: "OTR/L, SIT Certified",
    specialty: "Sensory Integration",
    treatmentType: "Both",
    conditions: ["Sensory Processing", "Autism Spectrum Disorder", "Anxiety"],
    location: { city: "Arlington", state: "VA" },
    bio: "Certified in Sensory Integration Therapy, Maya creates individualized sensory diets to help children regulate and thrive in daily activities.",
    philosophy: "Through carefully designed sensory experiences, children can develop better regulation skills and confidence in their bodies.",
    experience: "10 years",
    availability: "Tuesday-Saturday, 10am-6pm",
    isRecommended: true
  },
  {
    id: "3",
    name: "James Rodriguez",
    credentials: "RYT-500, Child Yoga Specialist",
    specialty: "Yoga & Mindfulness",
    treatmentType: "Alternative",
    conditions: ["Anxiety", "Sensory Processing", "ADHD"],
    location: { city: "Bethesda", state: "MD" },
    bio: "James teaches breathing techniques and gentle yoga specifically designed for neurodivergent children to manage anxiety and improve focus.",
    philosophy: "Mindful movement and breathing practices empower children with tools they can use anywhere, anytime to self-regulate.",
    experience: "8 years",
    availability: "Weekdays 3pm-7pm, Weekends 9am-2pm",
    isRecommended: false
  },
  {
    id: "4",
    name: "Dr. Emily Morrison",
    credentials: "PsyD, BCBA",
    specialty: "Behavioral Therapy",
    treatmentType: "Conventional",
    conditions: ["Autism Spectrum Disorder", "ADHD", "Developmental Delays"],
    location: { city: "Washington", state: "DC" },
    bio: "Board-certified behavior analyst specializing in Applied Behavior Analysis (ABA) with a naturalistic and compassionate approach.",
    philosophy: "ABA should be child-led and family-centered. I focus on building skills that matter most to each family's daily life.",
    experience: "12 years",
    availability: "Monday-Friday, 8am-4pm",
    isRecommended: false
  },
  {
    id: "5",
    name: "Lisa Chang",
    credentials: "LAc, Dipl. OM",
    specialty: "Acupuncture",
    treatmentType: "Alternative",
    conditions: ["Anxiety", "Sensory Processing", "ADHD"],
    location: { city: "Silver Spring", state: "MD" },
    bio: "Licensed acupuncturist with specialized training in pediatric acupuncture and non-needle techniques for children who may be needle-sensitive.",
    philosophy: "Traditional Chinese Medicine offers gentle, holistic support for nervous system regulation without reliance on medication.",
    experience: "14 years",
    availability: "Wednesday-Sunday, 11am-7pm",
    isRecommended: false
  },
  {
    id: "6",
    name: "Marcus Johnson",
    credentials: "PT, DPT, PCS",
    specialty: "Physical Therapy",
    treatmentType: "Conventional",
    conditions: ["Developmental Delays", "Sensory Processing", "Autism Spectrum Disorder"],
    location: { city: "Alexandria", state: "VA" },
    bio: "Pediatric physical therapist helping children develop gross motor skills, coordination, and confidence through movement-based interventions.",
    philosophy: "Every child deserves to move with joy and freedom. I create playful therapy sessions that build strength and coordination.",
    experience: "9 years",
    availability: "Monday-Thursday, 9am-5pm",
    isRecommended: true
  },
  {
    id: "7",
    name: "Rachel Goldstein",
    credentials: "MA, OTR/L",
    specialty: "Occupational Therapy",
    treatmentType: "Conventional",
    conditions: ["Dyslexia", "ADHD", "Developmental Delays"],
    location: { city: "Rockville", state: "MD" },
    bio: "Occupational therapist specializing in handwriting, fine motor skills, and executive function support for children with learning differences.",
    philosophy: "I help children develop the skills they need for school success while honoring their unique learning styles.",
    experience: "11 years",
    availability: "Monday-Friday, 2pm-7pm",
    isRecommended: false
  },
  {
    id: "8",
    name: "David Kim",
    credentials: "MT-BC",
    specialty: "Music Therapy",
    treatmentType: "Both",
    conditions: ["Autism Spectrum Disorder", "Anxiety", "Speech Delays"],
    location: { city: "Washington", state: "DC" },
    bio: "Board-certified music therapist using rhythm, melody, and sound to support communication, emotional regulation, and social connection.",
    philosophy: "Music is a universal language that can unlock communication and joy for neurodivergent children.",
    experience: "7 years",
    availability: "Tuesday-Saturday, 10am-6pm",
    isRecommended: true
  },
  {
    id: "9",
    name: "Sophia Martinez",
    credentials: "ATR-BC, LPAT",
    specialty: "Art Therapy",
    treatmentType: "Alternative",
    conditions: ["Anxiety", "Autism Spectrum Disorder", "Sensory Processing"],
    location: { city: "Falls Church", state: "VA" },
    bio: "Registered art therapist creating safe spaces for nonverbal expression and emotional processing through creative media.",
    philosophy: "Art provides a voice when words are difficult. I meet children in their creative process without judgment.",
    experience: "10 years",
    availability: "Monday, Wednesday, Friday 1pm-8pm",
    isRecommended: false
  },
  {
    id: "10",
    name: "Dr. Amanda Foster",
    credentials: "PhD, CCC-SLP, TSSLD",
    specialty: "Speech Therapy",
    treatmentType: "Conventional",
    conditions: ["Dyslexia", "Speech Delays", "Developmental Delays"],
    location: { city: "Bethesda", state: "MD" },
    bio: "Speech-language pathologist specializing in literacy development and reading intervention for children with dyslexia and language-based learning disabilities.",
    philosophy: "Reading challenges are neurological, not motivational. I use multisensory, structured approaches proven to help dyslexic learners succeed.",
    experience: "18 years",
    availability: "Monday-Thursday, 3pm-8pm",
    isRecommended: true
  },
  {
    id: "11",
    name: "Nia Williams",
    credentials: "E-RYT 200, Kids Yoga Certified",
    specialty: "Yoga & Mindfulness",
    treatmentType: "Alternative",
    conditions: ["Anxiety", "ADHD", "Sensory Processing"],
    location: { city: "Washington", state: "DC" },
    bio: "Experienced yoga instructor teaching breathing techniques and movement practices specifically designed for children with attention and anxiety challenges.",
    philosophy: "Breath is the bridge between body and mind. I teach children practical tools for self-regulation through gentle, accessible practices.",
    experience: "6 years",
    availability: "Weekends and weekday evenings",
    isRecommended: false
  },
  {
    id: "12",
    name: "Dr. Robert Thompson",
    credentials: "OTD, OTR/L",
    specialty: "Sensory Integration",
    treatmentType: "Conventional",
    conditions: ["Sensory Processing", "Autism Spectrum Disorder", "ADHD"],
    location: { city: "McLean", state: "VA" },
    bio: "Occupational therapist with doctorate-level training in sensory integration, helping children process sensory information more effectively.",
    philosophy: "When we understand a child's sensory needs, we can create environments where they feel safe, regulated, and ready to learn.",
    experience: "13 years",
    availability: "Monday-Friday, 8am-3pm",
    isRecommended: false
  }
]
